### ISSUE TITLE
How to use complex types

### ISSUE THREAD

**Issue by greg0ire** [Padam87/AttributeBundle#10]
I tried using the select and checkbox types. I get a 500 for the former saying that "the select type cannot be loaded", and for both, the `DefinitionType` does not have an `options` widget, and I think choices should be stored in this field shouldn't they ?

**Comment by Padam87** [comment]
"the select type cannot be loaded" was fixed by 1b59342079f2809607a0924022c35202b10e1ffd, this was not in 2.0.0, just created a new tag for this, 2.0.1.

The options are missing, and I have no idea why I have removed them during the 2.0 refactor.
https://github.com/Padam87/AttributeBundle/commit/996c9632f9c5975208346b643b5bcd6b6b7ec483#diff-52b5f24686a9d069e5db687bd2d247a8L26

**Comment by greg0ire** [comment]
I no longer have the 500 after upgrading :) . What do you plan on doing regarding the options ? Revert the change ?

**Comment by greg0ire** [comment]
Hum… I resurrected the OptionType in my tree, but something looks really weird : the Option entity has a name, but no value ?!? I would have expected to be able to create a "choices" option with some yaml as content, or something like that…

**Comment by Padam87** [comment]
The value will be the same as the name in the select's option list. I think there is no point in trying to create option values, since you can't be depending on these for anything, the user can change it anytime.

**Comment by greg0ire** [comment]
Oh ok, I did not realise the options were the choices…

**Comment by greg0ire** [comment]
I think there really is a point to create option values : the user may want to change the label for some reason, and in my experience, they do, while they "probably" won't change the value (in practice, when they do, they revert the change when they understand they broke something). Maybe we could even disable this field ?

**Comment by Padam87** [comment]
Yep, the value should be the option ID.

**Comment by greg0ire** [comment]
I am going to try to achieve that, I'll keep you posting with the results.

**Comment by Padam87** [comment]
https://github.com/Padam87/AttributeBundle/blob/master/Form/EventListener/AttributeSubscriber.php#L103

It should be simple, just change it to the ID here.

**Comment by greg0ire** [comment]
Indeed, I will try that.

**Comment by greg0ire** [comment]
In fact I have a requirement in my project : the code can be an ID, but it can also be a zip code, or anything unique and easy to export. I changed the `Option` entity to add a `value` field, and changed its form, and I am going to use that instead of the ID.

**Comment by Padam87** [comment]
:+1: That may be useful for others too. Value it is :)

**Comment by greg0ire** [comment]
\o/

**Comment by greg0ire** [comment]
I just pushed a branch to my fork named "portal". It contains various hacks / fixes for my project because I cannot really wait for you to fix all this. I separated commits that are "dirty" from other commits that you should be able to cherry-pick without problem if you want to.

**Comment by Padam87** [comment]
Thanks, great. Currently I'm writing some functional tests before starting messing around.
