### ISSUE TITLE
What is the entity options purpose

### ISSUE THREAD

**Issue by anis-marrouchi** [Padam87/AttributeBundle#28]
hello Everyone,
I'm trying to integrate AttributeBundle, and i would like to have an add example to see how things work together.  does the option entities represent the form field options?
Anyway, great job Adam and all the contributors!

**Comment by Padam87** [comment]
Hi Anis,

Yes, the options are for the choice fields, but unfortunately they are currently missing from the form. https://github.com/Padam87/AttributeBundle/issues/14

**Comment by Padam87** [comment]
I've just created a PR readding options to the form. You may also want to look at the 3.0 branch, it has a couple of fixes / cleanups.

**Comment by anis-marrouchi** [comment]
Thanks a lot for your prompt reply. I have followed your instructions. I'm trying now to add some attributes to an existing entity, the problem i'm facing is that the form prototype is empty. Am i missing something.
Here is my code (view side):
```javascript
<script>
    Schema = {
        addDefinition: function () {
            var prototype = $('#schema_definitions').data('prototype');
            var newItem = prototype.replace(/_name/g, $('#schema_definitions').children().length);

            $('#schema_definitions').append(newItem);
        }
    }
</script>
```
```twig
{% for attribute in form.attributes %}
    <li>{{ form_row(attribute) }}</li>
    {% endfor %}
<a class="btn btn-success" href="#" onclick="Schema.addDefinition();
        return false;">
    {% trans %}Add new item{% endtrans %}
</a>
<ul id="schema_definitions" data-prototype="{{ form_widget(form.attributes.vars.prototype)|e }}"></ul>
```

**Comment by Padam87** [comment]
Sorry the form configuration is missing a few things in the example.

Have you set the `prototype`options to `true`? Like so: https://github.com/Padam87/AttributeBundle/blob/master/Form/DefinitionType.php#L31
