### ISSUE TITLE
Definition with checkbox type and multiple options

### ISSUE THREAD

**Issue by DavidG04** [Padam87/AttributeBundle#35]
Hi,

I use your bundle in my project with SonataAdminBundle. I create Admin class to populate a schema with definition and options. All it's ok but when i try to use a definition with multiple options an error occured on database persist.

In fact the system try to register an array in string value.

In AttributeSubscriber class the createValueField method transform checkbox definition in choice definition with multiple and expanded options to true. All it's ok to display the field but not to persist the data.

Maybe i will try to serialize the data before persist and deserialize in pre set data ?

if you want my admin code and my template, it's with pleasure.

Excuse me for my english but it's very poor.

**Comment by Padam87** [comment]
Hi David,

I've created a PR for this. https://github.com/Padam87/AttributeBundle/pull/36

I'm not quite ready to merge it yet, because of the varchar(255) type of the value field. This could run out on occasion. Upgrading it to text would result in performance loss.

You can use that branch if you want before I merge it :)

**Comment by DavidG04** [comment]
thx

all it' ok, I just add a get method in the 'trait' to retrieve a value of attribute shortly

```php
    /**
     * get an attribute value by this key
     *
     * @param string $string
     *
     * @return mixed
     */
    public function get($string)
    {
        $result = null;
        foreach ($this->getAttributes() as $attribute) {
            if ($string == $attribute->getDefinition()->getName()) {
                $result = $attribute->getValue();
            }
        }

        return $result;
    }
```
the call

```php
$valueAttribute = $myObject->get('keyAttribute');
```
thank's again for this PR, and i try to send the admin code quickly :)
